### ISSUE TITLE
combining the ninja files into one exe 

### ISSUE THREAD

**Issue by malashhab** [ErAz7/Ninja#3]
hi there i been wondering if i could combine all the files in the ninja directory into one exe so the victim doesn't suspect anything i edited the files and the ports and i used a dns i only need all the files to be in one exe any ideas would appreciated

**Comment by ErAz7** [comment]
Hey
the only necessary file is `constants.json`. Yes it's possible to put it inside the .exe file but it won't be customizable and that's why it's placed out of the executable. However, there might be ways to bundle them together into a single exe

**Comment by malashhab** [comment]
> Hey the only necessary file is `constants.json`. Yes it's possible to put it inside the .exe file but it won't be customizable and that's why it's placed out of the executable. However, there might be ways to bundle them together into a single exe

can you please give me a link to a tutorial about combining a json with an exe

**Comment by ErAz7** [comment]
well have not tried doing this before but this looks relevant:

[bind join two more files into single executable file](https://operating-systems.wonderhowto.com/how-to/bind-join-two-more-files-into-single-executable-file-0155020/)

however, if you have access to the target, it's recommended to use [single click installer for windows](https://github.com/ErAz7/Ninja#single-click-installer) which will copy the files to a specific path and start Ninja as a service (will start on every boot in background). This would be better since the Ninja process will be always running even after restarting the machine
